version: "2.0"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - DEBUG=${DEBUG}
      - SERVER_PORT=${SERVER_PORT}
      - NEO4J_URL=${NEO4J_URL}
      - NEO4J_USER=${NEO4J_USER}
      - NEO4J_PASSWORD=${NEO4J_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_RECEIVER_DEPLOY_QUEUE=${REDIS_RECEIVER_DEPLOY_QUEUE}
      - REDIS_WITHDRAWER_QUEUE=${REDIS_WITHDRAWER_QUEUE}
      - REDIS_WITHDRAWER_DB=${REDIS_WITHDRAWER_DB}
      - REDIS_RECEIVER_DEPLOYED_QUEUE=${REDIS_RECEIVER_DEPLOYED_QUEUE}
      - REDIS_RECEIVER_DB=${REDIS_RECEIVER_DB}
      - WEB3_HTTP_PROVIDER=${WEB3_HTTP_PROVIDER}
      - TRANSACTION_SIGNER_PRIVATE_KEY=${TRANSACTION_SIGNER_PRIVATE_KEY}
      - TRANSACTION_SIGNER_PRIVATE_KEY_HEX=${TRANSACTION_SIGNER_PRIVATE_KEY_HEX}
      - TRANSACTION_SIGNER_PUBLIC_KEY=${TRANSACTION_SIGNER_PUBLIC_KEY}
      - BANK_ID=${BANK_ID}
      - WATCHER_INTERVAL_MILLISECONDS=${WATCHER_INTERVAL_MILLISECONDS}
      - JWT_SECRET=${JWT_SECRET}
    ports:
      - 4000:4000
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      ganache:
        condition: service_started
