version: "2.0"

services:
  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    entrypoint:
      - node
      - /app/ganache-core.docker.cli.js
      - --networkId
      - "5777"
      - --hostname
      - "0.0.0.0"
      - --quiet
      - --account="${PRIVATE_KEY},99999999999999999999999999999999999999999999999999999999999999999999999999999"
