version: "2.0"

services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    ports:
      - 4000:4000
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      ganache:
        condition: service_started
