version: "2.0"

services:
  centralized-eth-erc20-payments:
    build:
      context: .
    environment:
      - SERVER_PORT=4000
      - NEO4J_URL=neo4j://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=test
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 4000:4000
    depends_on:
      neo4j:
        condition: service_healthy
      redis:
        condition: service_healthy
      ganache:
        condition: service_started
